import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  startSidebar: ['intro', {type: 'autogenerated', dirName: 'start'}],
  tutorialSidebar: [
    'guides',
    'reference',
    'troubleshoot',
    {type: 'category', label: 'Authentication', items: [{type: 'autogenerated', dirName: 'authenticate'}]},
    {type: 'category', label: 'Authorization', items: [{type: 'autogenerated', dirName: 'authorize'}]},
    {type: 'category', label: 'Credentials', items: [{type: 'autogenerated', dirName: 'credentials'}]},
    {type: 'category', label: 'Messaging', items: [{type: 'autogenerated', dirName: 'messaging'}]},
    {type: 'category', label: 'Applications', items: [{type: 'autogenerated', dirName: 'apps'}]},
    {type: 'category', label: 'Examples', items: [{type: 'autogenerated', dirName: 'examples'}]},
  ],
};

export default sidebars;
